name: Call Terraform
on: 
  workflow_call:
    inputs:
      directory_path:
        required: true
        type: string

env:
  TF_VERSION: 1.1.7
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ap-northeast-2

jobs:
  plan:
    runs-on: ubuntu-20.04
    outputs:
      GIT_DIFF: ${{ steps.get-diff.outputs.diff }}
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Print path
        run: |
          echo ${{ inputs.directory_path }}
