name: Run Terraform

on: [pull_request]

env:
  TF_VERSION: 1.1.7

jobs:
  Init:
    runs-on: ubuntu-22.04
    outputs:
      GIT_DIFF_DIRS: ${{ steps.generate.outputs.GIT_DIFF_DIRS }}
    steps:
      # - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v4
        with:
          SEPARATOR: ','
      - name: Export Directories
        run: |
          echo GIT_DIFF_DIRS=$(echo $GIT_DIFF | tr , \\n | xargs -n 1 dirname | uniq | tr '\n' ',') >> $GITHUB_ENV
      - id: generate
        run: |
          JOB_STRATEGY_MATRIX=$(node -e "console.log(JSON.stringify(process.env.GIT_DIFF_DIRS.split(',').filter(c => c)));")
          echo "::set-output name=GIT_DIFF_DIRS::$JOB_STRATEGY_MATRIX"
  Plan:
    needs: Init
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        job: ${{ fromJson(needs.prepare.outputs.GIT_DIFF_DIRS) }}
      max-parallel: 2
    steps:
      - run: echo "This is job ${{ matrix.job }}"
